### ISSUE TITLE
Implement HTTP web server in C

### ISSUE THREAD

**Issue by mubeena12** [mubeena12/final-project-assignment-YoctoNanoWebContainer#2]
- Server should listen on the local host and bind to port 80
- Server should return a basic HTML page when accessed from a browser 
- Server should be able to spawn a thread/process for the lifetime of the connection 

DoD: Able to send an HTTP request to the host running the web server and an HTML page is returned

Blockers: None

**Comment by MendezBytes** [comment]
DoD verified: Navigating to the ip of the server and appending the path of a file, returns the html page.

Example 1: Navigating to a generic web page called test.html


![Image](https://github.com/mubeena12/final-project-assignment-YoctoNanoWebContainer/assets/13033849/371f2bd3-e0c3-4e64-a252-826694cfb627)


Example 2: Navigating to a piece of artwork created by me:

![Image](https://github.com/mubeena12/final-project-assignment-YoctoNanoWebContainer/assets/13033849/2475aaa3-77d7-4f80-abad-8dafe676ac4c)

Example 3: Navigating to several different files in the same directory 


![Image](https://github.com/mubeena12/final-project-assignment-YoctoNanoWebContainer/assets/13033849/307e2b48-e6bd-4132-95ee-ab4347ad3b3a)



Changes made are primarily here:

https://github.com/cu-ecen-aeld/final-project-Silex93/commit/874676b891106547d9a59476ca3c553a8d943a85

Complete list of file changes: 
https://github.com/cu-ecen-aeld/final-project-Silex93/compare/Driver_Working...main




For this implementation, i used the aesdsocket code as a base. I needed to modify that code to remove the functionality of locking and unlocking the mutex as well as other extras such as the ioctl calls. Upon reading more about HTTP, i realized i just needed to handle how the request and response is handled and sent.

Here is the main thread function that handles client requests:


```C
	//First ensure that we recieved a GET request
  	regmatch_t matches[2];
  	res = regexec(&http_get_regex, recv_buffer, 2, matches, 0);
  	if(res == 0){
  	//Matches Get request format
  	//We extract the filename being requested from the url if present
        recv_buffer[matches[1].rm_eo] = '\0';
       const char *url_encoded_file_name = recv_buffer + matches[1].rm_so;
			
	//Decode the URL encoded filename
        char *file_name = decode_url(url_encoded_file_name);

        // Get the file extension
        char file_ext[16];
        strcpy(file_ext, get_file_extension(file_name));

        
        // Build the HTTP responses
        char *response = (char *)malloc(BUFFER_SIZE * 2 * sizeof(char));
        size_t response_len;
        build_http_response(file_name, file_ext, response, &response_len);

        // send HTTP response to client
        send(client_socket, response, response_len, 0);

        free(response);
        free(file_name);
```


The two utility functions required was mainly to decode a URL encoded string to a regular one and one to map the MIME type based on the file extension being requested.

I have left the ability to daemonize the application as this is how it would be ran in the final scenario.

IN building the HTTP response, i utilized the function from https://github.com/JeffreytheCoder/Simple-HTTP-Server/blob/939ede03cbfb45a5441da511b62b588962453358/server.c#L96C49-L96C49
as in essence i require the exact same functionality. I would edit it further for the next sprint as this must then act as a reverse proxy

```C
void build_http_response(const char *file_name, 
                        const char *file_ext, 
                        char *response, 
                        size_t *response_len) {
    // build HTTP header
    const char *mime_type = get_mime_type(file_ext);
    char *header = (char *)malloc(BUFFER_SIZE * sizeof(char));
    snprintf(header, BUFFER_SIZE,
             "HTTP/1.1 200 OK\r\n"
             "Content-Type: %s\r\n"
             "\r\n",
             mime_type);

    // if file doesnt exist, response is 404 Not Found
    int file_fd = open(file_name, O_RDONLY);
    if (file_fd == -1) {
        snprintf(response, BUFFER_SIZE,
                 "HTTP/1.1 404 Not Found\r\n"
                 "Content-Type: text/plain\r\n"
                 "\r\n"
                 "404 Not Found");
        *response_len = strlen(response);
        return;
    }

    // get file size for Content-Length
    struct stat file_stat;
    fstat(file_fd, &file_stat);


    // copy header to response buffer
    *response_len = 0;
    memcpy(response, header, strlen(header));
    *response_len += strlen(header);

    // copy file to response buffer
    ssize_t bytes_read;
    while ((bytes_read = read(file_fd, 
                            response + *response_len, 
                            BUFFER_SIZE - *response_len)) > 0) {
        *response_len += bytes_read;
    }
    free(header);
    close(file_fd);
}
```


For testing i utilized the Jetson Nano 2gb image hosted here: https://developer.nvidia.com/embedded/l4t/r32_release_v5.1/r32_release_v5.1/jeston_nano_2gb/jetson-nano-2gb-jp451-sd-card-image.zip
