### ISSUE TITLE
Setup Yocto repository part 1

### ISSUE THREAD

**Issue by mubeena12** [mubeena12/final-project-assignment-YoctoNanoWebContainer#3]
- Setup the host machine with the necessary packages to build the Yocto Linux Distribution 
- Create a Yocto repository for the target Jetson nano hardware
- Install dependencies to install the docker
- Configure to yocto build to Install the docker

DoD: Successfully build the image and able to program on Jetson nano

Blockers: None

**Comment by MendezBytes** [comment]
DOD: Image builds and loads fine

Issue was reassigned to Mubeena and Daniel
Related repos:

Daniel : https://github.com/Silex93/YoctoWebServer/commit/5633cbb5a1202b95feb48ec25544272a45ccf296

Mubeena :https://github.com/cu-ecen-aeld/final-project-mubeena12/commit/3fee30a529681bb84352756b1855fcf951ccdee2
