### ISSUE TITLE
Docker deployment continuation

### ISSUE THREAD

**Issue by MendezBytes** [mubeena12/final-project-assignment-YoctoNanoWebContainer#5]
- Modify the previous dockerfile to pull web server code
- Build the web server code and deploy it
- Configure docker container to expose and properly forward ports required for the web server
- Run a shell script to verify proper container setup

DoD : The docker image successfully builds and a container is created with the running web server code (in it's previous state)

Blockers : Web Server code must be functional

**Comment by mubeena12** [comment]
Commit link: https://github.com/cu-ecen-aeld/final-project-mubeena12/commit/303244fe613b5db696c8fdaed622e9922a59c468

DoD Verified:
Integrated [SensorMonitoringWebApp](https://github.com/Silex93/SensorMonitoringWebApp) and [SensorMonitoringDriver]git@github.com:cu-ecen-aeld/final-project-Silex93.git

Modified Dockerfile to point to SensorMonitoringWebApp.
Port is exposed to 5500:5500

Added custom docker-app layer in the yocto project.
Board is up and running with both webapp and postgresql

On the board:
cd /etc/init.d/
./start-stop-webapp.sh start

![Image](https://github.com/mubeena12/final-project-assignment-YoctoNanoWebContainer/assets/38264552/efe0348e-b11f-48dc-902b-b72bdb408494)

On to the browser: 
http://jetson-nano-2gb-devkit:5500/

![Image](https://github.com/mubeena12/final-project-assignment-YoctoNanoWebContainer/assets/38264552/1a50ba93-87c8-4346-8ff8-9bf0b618ebb8)
