### ISSUE TITLE
Setup PostGresql DB

### ISSUE THREAD

**Issue by MendezBytes** [mubeena12/final-project-assignment-YoctoNanoWebContainer#8]
- Modify dockerfile to install and startup PostGreSQL DB
- Modify test script to check if PostGreSQL is up and running

DoD : PostgreSQL DB is running once the container is up and the test script confirms this.

Blockers: Previous container is in a working state .

**Comment by mubeena12** [comment]
Commit link for sprint1: https://github.com/cu-ecen-aeld/final-project-mubeena12/commit/8d325148ffa96d81e1b29898d70036020b348128

DoD Verified

Testing the containers and verifying the database:
![Image](https://github.com/mubeena12/final-project-assignment-YoctoNanoWebContainer/assets/38264552/5d7207a3-7bfd-4b1e-b12d-bedfd5055cc8)

Built the docker containers for webapp and Postgres
![Image](https://github.com/mubeena12/final-project-assignment-YoctoNanoWebContainer/assets/38264552/1a37cf16-8b45-49fa-b91f-78fb9752f309)
